sudo: required

dist: trusty

before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended

script:
- xelatex -interaction=nonstopmode -halt-on-error main.tex

install:
- xelatex -interaction=nonstopmode -halt-on-error main.tex

notifications:
  email: false